/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import com.smsimobile.data.TBLCustomer;
import com.smsimobile.form.CustomerForm;


/** 

/** 
 * MyEclipse Struts
 * Creation date: 09-30-2009
 * 
 * XDoclet definition:
 * @struts.action path="/import" name="importForm" scope="request" validate="true"
 */
public class PhoneBookAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		
		String forwardText = null; 
		HttpSession session = request.getSession();
		String userName = session.getAttribute("userName").toString();
		CustomerForm customerForm = (CustomerForm) form;
      
	     String custID = customerForm.getCustID();
	     String custName = new String(customerForm.getCustName().getBytes("ISO8859-1"), "UTF-8");
	     String custType = customerForm.getCustType();
	  
	     TBLCustomer customerDB = new TBLCustomer();
	   
	     customerDB.AddCustomer(custID, custName, custType, userName);
	    		
	     List customerList = customerDB.GetCustomerList("", "");
		 request.setAttribute("customerList", customerList);
	     
		forwardText = "success";

	   return mapping.findForward(forwardText);
	}
}