/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.jsmpp.InvalidResponseException;
import org.jsmpp.PDUException;
import org.jsmpp.bean.Alphabet;
import org.jsmpp.bean.BindType;
import org.jsmpp.bean.DataCoding;
import org.jsmpp.bean.ESMClass;
import org.jsmpp.bean.GeneralDataCoding;
import org.jsmpp.bean.MessageClass;
import org.jsmpp.bean.NumberingPlanIndicator;
import org.jsmpp.bean.RegisteredDelivery;
import org.jsmpp.bean.SMSCDeliveryReceipt;
import org.jsmpp.bean.TypeOfNumber;
import org.jsmpp.extra.NegativeResponseException;
import org.jsmpp.extra.ResponseTimeoutException;
 
import org.jsmpp.session.BindParameter;
import org.jsmpp.session.SMPPSession;


import com.smsimobile.data.SMSTemplateDB;
import com.smsimobile.data.SendSMSDB;
import com.smsimobile.data.TBLCustomer;
import com.smsimobile.form.SendSMSForm;
 
public class SendSMSConfimAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		SendSMSForm sendSMSForm = (SendSMSForm) form;
		String confim 	= sendSMSForm.getConfim();
		String edit		= sendSMSForm.getEdit();
		
		if(confim!=null){
		HttpSession session = request.getSession();
		List recipientList = new ArrayList();
		String userName = session.getAttribute("userName").toString();
		String sender = session.getAttribute("sender").toString();
		String message = session.getAttribute("message").toString();
		String sendDate = session.getAttribute("sendDate").toString();
		int unit = Integer.parseInt(session.getAttribute("unit").toString());
		double cost = Double.parseDouble(session.getAttribute("cost").toString());
		
		String serviceName = "SMS Service";
		String alertMessage = null;
		System.out.println("----------------------- SEND SMS -----------------------");
		
		String systemHost = "127.0.0.1";
		int systemPort = 10002;//your PORT
		String systemId = "quppee";
		String systemPass = "quppee";
		SMPPSession session1 = new SMPPSession();
		try {
			session1.connectAndBind(systemHost, systemPort, new BindParameter(BindType.BIND_TX, systemId, systemPass, null, 
            		TypeOfNumber.UNKNOWN, NumberingPlanIndicator.UNKNOWN, null));
        } catch (IOException e) {
            System.err.println("Failed connect and bind to host");
            e.printStackTrace();
            System.exit(-1);
        }
        
        System.out.println("connected");   
		
        RegisteredDelivery registeredDelivery = new RegisteredDelivery();
		registeredDelivery.setSMSCDeliveryReceipt(SMSCDeliveryReceipt.DEFAULT);
    	
    	DataCoding dataCoding = null;
		byte[] data = null;
		String period = null; // set period to null
		try {
			dataCoding = new GeneralDataCoding(false,
					true, MessageClass.CLASS1, Alphabet.ALPHA_UCS2);
			
				data = message.getBytes("UTF-16BE");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		SendSMSDB sendSMSDB = new SendSMSDB();
		
		recipientList = (List) session.getAttribute("recipientList");
		List recipientStatusList = new ArrayList();
		
		for(int i=0; i<recipientList.size(); i++) {
            SendSMSForm smsForm = (SendSMSForm) recipientList.get(i);
            String status = null;
            String recipient = smsForm.getCustID();
            
            try {
            	//----- SEND SMS -----
 
            	//	sendFinal.sendSMS(message, sender, recipient);
            	
            		try {
                    	
                    	String messageId = session1.submitShortMessage(
            					null,
            					TypeOfNumber.ALPHANUMERIC,
            					NumberingPlanIndicator.UNKNOWN, sender,
            					TypeOfNumber.INTERNATIONAL,
            					NumberingPlanIndicator.UNKNOWN, recipient,
            					new ESMClass(), (byte) 0, (byte) 1,
            					period, null,
            					registeredDelivery, (byte) 0, dataCoding,
            					(byte) 0, data);
                    	
                        System.out.println("Message submitted, message_id is " + messageId);
                        
                        sendSMSDB.AddSMS(recipient, message, sender, sendDate, unit, cost, userName);
           //  Request Status ///
                        
                   
           // /////            
                        
                    } catch (PDUException e) {
                        // Invalid PDU parameter
                        System.err.println("Invalid PDU parameter");
                        alertMessage = "Invalid PDU parameter";
                        e.printStackTrace();
                    } catch (ResponseTimeoutException e) {
                        // Response timeout
                        System.err.println("Response timeout");
                        alertMessage = "Response timeout";
                        e.printStackTrace();
                    } catch (InvalidResponseException e) {
                        // Invalid response
                        System.err.println("Receive invalid respose");
                        alertMessage = "Receive invalid respose";
                        e.printStackTrace();
                    } catch (NegativeResponseException e) {
                        // Receiving negative response (non-zero command_status)
                        System.err.println("Receive negative response");
                        alertMessage = "Receive negative response";
                        e.printStackTrace();
                    } catch (IOException e) {
                        System.err.println("IO error occur");
                        alertMessage = "IO error occur";
                        e.printStackTrace();
                    }
            		
			} catch (Exception e) {
				e.printStackTrace();
			}
            
		}
		TBLCustomer tblcustomer = new TBLCustomer();
		SMSTemplateDB smstemplateDB = new SMSTemplateDB();
		List customerList; List smsTemplateList;
		try {
			customerList = tblcustomer.GetCustomerList("", "");
			request.setAttribute("customerList", customerList);
			smsTemplateList= smstemplateDB.GetSMSTemplateList("");
			request.setAttribute("smsTemplateList", smsTemplateList);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		session1.unbindAndClose();
		
		request.setAttribute("alertMessage", alertMessage);
		}
		if(edit!=null){
			HttpSession session = request.getSession();
			String recipient = session.getAttribute("recipient").toString();
			String sender = session.getAttribute("sender").toString();
			String message = session.getAttribute("message").toString();
			String unit = session.getAttribute("unit").toString();
			String cost = session.getAttribute("cost").toString();
			cost = cost.replace(".0", "");
			
			request.setAttribute("recipient", recipient);
			request.setAttribute("sender", sender);
			request.setAttribute("message", message);
			request.setAttribute("unit", unit);
			request.setAttribute("cost", cost);
			
			TBLCustomer tblcustomer = new TBLCustomer();
			SMSTemplateDB smstemplateDB = new SMSTemplateDB();
			List customerList; List smsTemplateList;
			try {
				customerList = tblcustomer.GetCustomerList("", "");
				request.setAttribute("customerList", customerList);
				smsTemplateList= smstemplateDB.GetSMSTemplateList("");
				request.setAttribute("smsTemplateList", smsTemplateList);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		return mapping.findForward("success");
	}
}