/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smsimobile.data.SMSTemplateDB;
import com.smsimobile.data.TypeSMSTemplateDB;
import com.smsimobile.form.SMSTemplateForm;

public class SMSTemplateAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		
		String forwardText = null; 
		HttpSession session = request.getSession();
		String userName = session.getAttribute("userName").toString();
		SMSTemplateForm smstemplateForm = (SMSTemplateForm) form;
      
	     String description = new String(smstemplateForm.getDescription().getBytes("ISO8859-1"), "UTF-8");
	     String type = smstemplateForm.getType();
	     String descriptionHD = new String(smstemplateForm.getDescriptionHD().getBytes("ISO8859-1"), "UTF-8");
	     String typeHD = smstemplateForm.getTypeHD();
	  
	     String save = smstemplateForm.getSave();
	     String update = smstemplateForm.getUpdate();
	     
	     SMSTemplateDB smstemplateDB = new SMSTemplateDB(); 
	    
	     if(save!=null){
	    	 smstemplateDB.AddTemplate(description, type);
	     }
	     if(update!=null){
	    	 smstemplateDB.UpdateTemplate(description, type, descriptionHD, typeHD);
	     }
	     
		List smsTemplateList = smstemplateDB.GetSMSTemplateList("");
		request.setAttribute("smsTemplateList", smsTemplateList);
	     
		TypeSMSTemplateDB typeSMSTemplateDB = new TypeSMSTemplateDB();
		List TypeSMSList = typeSMSTemplateDB.GetTpyeSMSList();
		request.setAttribute("TypeSMSList", TypeSMSList);
		
		forwardText = "success";

	   return mapping.findForward(forwardText);
	}
}