/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.form;
import org.apache.struts.action.ActionForm;

public class CustomerForm extends ActionForm {
	
	private String custID;
	private String custName;
	private String hdCustID;
	
	public CustomerForm(){};
	public CustomerForm (String custID, String custName){
		super();
		this.custID 	= custID;
		this.custName	= custName;
}
	
	public String getCustID() {
		return custID;
	}
	public void setCustID(String custID) {
		this.custID = custID;
	}
	public String getCustName() {
		return custName;
	}
	public void setCustName(String custName) {
		this.custName = custName;
	}
	public String getHdCustID() {
		return hdCustID;
	}
	public void setHdCustID(String hdCustID) {
		this.hdCustID = hdCustID;
	}

} 