/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.form;
import org.apache.struts.action.ActionForm;

public class CustomerForm extends ActionForm {
	
	private String custID;
	private String custName;
	private String hdCustID;
	private String custType;
	private String typeName;
	
	private String save;
	private String update;
	
	public CustomerForm(){};
	public CustomerForm (String custID, String custName, String custType, String typeName){
		super();
		this.custID 	= custID;
		this.custName	= custName;
		this.custType	= custType;
		this.typeName	= typeName;
}
	
	public String getCustID() {
		return custID;
	}
	public void setCustID(String custID) {
		this.custID = custID;
	}
	public String getCustName() {
		return custName;
	}
	public void setCustName(String custName) {
		this.custName = custName;
	}
	public String getHdCustID() {
		return hdCustID;
	}
	public void setHdCustID(String hdCustID) {
		this.hdCustID = hdCustID;
	}
	public String getCustType() {
		return custType;
	}
	public void setCustType(String custType) {
		this.custType = custType;
	}
	public String getSave() {
		return save;
	}
	public void setSave(String save) {
		this.save = save;
	}
	public String getUpdate() {
		return update;
	}
	public void setUpdate(String update) {
		this.update = update;
	}
	public String getTypeName() {
		return typeName;
	}
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

} 