/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.upload.FormFile;

public class ImportForm extends ActionForm {
	
	private String type;
	private FormFile theFile;
	private String loginUsername;
	
/*	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request ) {
		ActionErrors errors = new ActionErrors();

		if( getTheFile() == null) {
			errors.add("theFile",new ActionMessage("error.name.required"));
		}
		return errors; 
	} */
	
	public String getLoginUsername() {
		return loginUsername;
	}
	public void setLoginUsername(String loginUsername) {
		this.loginUsername = loginUsername;
	}
	public FormFile getTheFile() {
		return theFile;
	}
	  public void setTheFile(FormFile theFile) {
	    this.theFile = theFile;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
} 