/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-23-2009
 * 
 * XDoclet definition:
 * @struts.form name="phonBookForm"
 */
public class PhonBookForm extends ActionForm {
	/*
	 * Generated Methods
	 */
		private String name = null;
		private String phone = null;
		private String chk_box = null;
		private String  loginUsername = null;
		private String id = null;
		private String [] empIdSelect;
		private String numphone = null;
		private String chk_box1[];
		private String mobile [];
		private String Mid [];
		private String username = null;

		
		public String getNumphone() {
			return numphone;
		}

		public void setNumphone(String numphone) {
			this.numphone = numphone;
		}



	public String getId() {
			return id;
		}

		public void setId(String id) {
			this.id = id;
		}

	public String getLoginUsername() {
			return loginUsername;
		}

		public void setLoginUsername(String loginUsername) {
			this.loginUsername = loginUsername;
		}



	public String getChk_box() {
			return chk_box;
		}

		public void setChk_box(String chk_box) {
			this.chk_box = chk_box;
		}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String[] getMid() {
		return Mid;
	}

	public void setMid(String[] mid) {
		Mid = mid;
	}

	public String[] getMobile() {
		return mobile;
	}

	public void setMobile(String[] mobile) {
		this.mobile = mobile;
	}

	public String[] getChk_box1() {
		return chk_box1;
	}

	public void setChk_box1(String[] chk_box1) {
		this.chk_box1 = chk_box1;
	}

	public void setEmpIdSelect(String[] empIdSelect) {
		this.empIdSelect = empIdSelect;
	}

	public String[] getEmpIdSelect() {
		return empIdSelect;
	}


}