/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.form;

import org.apache.struts.action.ActionForm;

public class SendSMSForm extends ActionForm {
	
	private String custID;
	private String hdCustID;
	private String description;
	private String hdDescription;
	private String sendName;
	private String word;
	private String baht;
	
	private String sendType;
	private String sendDateTime;
	
	private String userName;
	
	private String date;
	private String time;
	
	private int unit;
	private double cost;
	
	private String confim;
	private String edit;
	
	public String getCustID() {
		return custID;
	}
	public void setCustID(String custID) {
		this.custID = custID;
	}
	public String getHdCustID() {
		return hdCustID;
	}
	public void setHdCustID(String hdCustID) {
		this.hdCustID = hdCustID;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getHdDescription() {
		return hdDescription;
	}
	public void setHdDescription(String hdDescription) {
		this.hdDescription = hdDescription;
	}
	public String getWord() {
		return word;
	}
	public void setWord(String word) {
		this.word = word;
	}
	public String getSendName() {
		return sendName;
	}
	public void setSendName(String sendName) {
		this.sendName = sendName;
	}
	public String getBaht() {
		return baht;
	}
	public void setBaht(String baht) {
		this.baht = baht;
	}
	public String getSendType() {
		return sendType;
	}
	public void setSendType(String sendType) {
		this.sendType = sendType;
	}
	public String getSendDateTime() {
		return sendDateTime;
	}
	public void setSendDateTime(String sendDateTime) {
		this.sendDateTime = sendDateTime;
	}
	public int getUnit() {
		return unit;
	}
	public void setUnit(int unit) {
		this.unit = unit;
	}
	public double getCost() {
		return cost;
	}
	public void setCost(double cost) {
		this.cost = cost;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public String getTime() {
		return time;
	}
	public void setTime(String time) {
		this.time = time;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getConfim() {
		return confim;
	}
	public void setConfim(String confim) {
		this.confim = confim;
	}
	public String getEdit() {
		return edit;
	}
	public void setEdit(String edit) {
		this.edit = edit;
	}

} 