/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.form;

import org.apache.struts.action.ActionForm;

public class SendSMSForm extends ActionForm {
	
	private String custID;

	public String getCustID() {
		return custID;
	}
	public void setCustID(String custID) {
		this.custID = custID;
	}
} 