/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.form;
import org.apache.struts.action.ActionForm;

public class SMSTemplateForm extends ActionForm {
	
	private String description;
	
	public SMSTemplateForm(){};
	public SMSTemplateForm (String description){
		super();
		this.description 	= description;
}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}

} 