/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smsimobile.form;
import org.apache.struts.action.ActionForm;

public class SMSTemplateForm extends ActionForm {
	
	private String description;
	private String type;
	
	public SMSTemplateForm(){};
	public SMSTemplateForm (String description, String type){
		super();
		this.description 	= description;
		this.type 	= type;
}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}

} 